# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicPlayerControl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicPlayerControl

  target 'MusicPlayerControlTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MusicPlayerControlUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
